### ISSUE TITLE
ConnectionRefusedError: [WinError 10061] because the target machine actively refused, unable to connect.

### ISSUE THREAD

**Issue by LoeChu** [GoverSky/HTMLTestRunner#1]
When I used HTMLTestRunner to generate test report, I encountered an error: ConnectionRefusedError:WinError[10061]  because the target machine actively refused, unable to connect.

**Comment by GoverSky** [comment]
Please show me the code or the screenshot of your error

**Comment by LoeChu** [comment]
![image](https://user-images.githubusercontent.com/19582734/37394324-6ad28a00-27ae-11e8-91e5-24783800a0af.png)
![image](https://user-images.githubusercontent.com/19582734/37394332-7383c0a6-27ae-11e8-9662-d99fbce9b191.png)
Test case execution fails to generate test report and error, all cases performed by report can be generated

**Comment by GoverSky** [comment]
Please update your chromedriver to the latest version，另外用中文沟通是不是更轻松些o(￣▽￣)d

**Comment by LoeChu** [comment]
哈哈，大神原来是中国人，但是我更新了驱动，又发生了上面的错误
![Uploading image.png…]()
我把原来执行不通过的用例改成能通过就可以生成了，发现只有用例失败的时候不能生成，应该和驱动没关系

**Comment by GoverSky** [comment]
因为失败和错误的用例要调用截图功能，你的selenium和chromedriver 截图功能失效了，可能其中一个版本低了，你可以单独用selenium试一下driver.get_screenshot_as_base64()，不行就把selenium也升级一下吧

**Comment by LoeChu** [comment]
好的，多谢大神：）
